#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 14 11:58:47 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim ShAnTestbench_behav -key {Behavioral:sim_1:Functional:ShAnTestbench} -tclbatch ShAnTestbench.tcl -view /home/it/digital_system/Digital_System_Design/lab2/task4/fulladder4bittestbench_behav.wcfg -log simulate.log"
xsim ShAnTestbench_behav -key {Behavioral:sim_1:Functional:ShAnTestbench} -tclbatch ShAnTestbench.tcl -view /home/it/digital_system/Digital_System_Design/lab2/task4/fulladder4bittestbench_behav.wcfg -log simulate.log

